name: linux_build
on:
  push:
    branches: [ main ]
    
jobs:
  build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Linux build dependency
        run: |
          sudo apt update
          sudo apt install -y ninja-build libgtk-3-dev libblkid-dev
          
      - name: Checkout source code
        uses: actions/checkout@v2
      
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'
          
      - name: Import Flutter Package
        run: |
          flutter pub get
          
      - name: Build Linux App
        run: |
          flutter build linux --release
          
      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v3
        with:
          type: 'zip'
          name: file_crypto_linux_x64.zip
          path: ./build/linux/x64/release/bundle
